name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            fwal/setup-swift@v1
      with:
        swift-version: "5.3.0"
    - name: Build
      run: swift build

  system-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: swift build          
    - name: Run system tests
      run: bash test.sh
 
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Run unit tests
      run: swift test