name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setting:

    runs-on: ubuntu-latest

    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3.0"
    
    steps:
    - name: Setup Swift
      run: swift -version
      
