name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
    - uses: actions/checkout@v2
    - name: Build
      uses: Didstopia/SwiftAction@v1.0.3
      with:
          swift-action: build
