name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
 
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
      with:
        swift-version: "5.3.0"
    - uses: actions/checkout@v2
    - run: swift build    
  
  system_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: bash test.sh
  
  unit_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: swift test
