name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Swift Action
        uses: Didstopia/SwiftAction@v1.0.1
        with:
          swift-action: 'build'
      - name: Run build
        run: swift build
