name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
      with:
        swift-version: "5.3.0"
    - uses: actions/checkout@v2
    - name: Build   
      run: swift build
  system-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run System Test
      run: bash Test.sh
