name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
      with:
        swift-version: "5.3.0"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Package
      run: swift build -v
    - name: Run test.sh
      run: bash test.sh
  
    
