name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  setting:
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@v1
        with:
            swift-version: "5.3.0"
      - run: swift -version
